#Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
#Fabric Properties
minecraft_version=26.2
minecraft_version_range=~26.2
loader_version=0.19.3
loom_version=1.16.3
# Mod Properties
mod_id=odin
mod_name=Odin (Unofficial 26.2 Port)
mod_description=Unofficial Minecraft 26.2 port of the Odin Hypixel SkyBlock QoL mod
mod_version=0.3.2+mc26.2.port.1
maven_group=io.github.hawkzlol
archives_base_name=odin-fabric
# Mod Dependencies
fabric_kotlin_version=1.13.12+kotlin.2.4.0
fabric_api_version=0.154.2+26.2
modmenu_version=20.0.1
devauth_version=1.2.2
commodore_version=1.0.1
iris=1.11.2+26.2-fabric
# Other Properties
kotlin_version=2.4.0
kotlin.code.style=official
